USE [db_ayni_personal_servidorpublico]
GO

insert into [dbo].[catalogo] (ID_CATALOGO, CODIGO_CATALOGO, DESCRIPCION_CATALOGO, ACTIVO, ELIMINADO, FECHA_CREACION, USUARIO_CREACION, IP_CREACION) values(1, 6, 'Tipo de documento de identidad', 1, 0, GETDATE(), 'ADMIN', 'SISTEMAS')
insert into [dbo].[catalogo] (ID_CATALOGO, CODIGO_CATALOGO, DESCRIPCION_CATALOGO, ACTIVO, ELIMINADO, FECHA_CREACION, USUARIO_CREACION, IP_CREACION) values(2, 12, 'Nivel Instancia', 1, 0, GETDATE(), 'ADMIN', 'SISTEMAS')
insert into [dbo].[catalogo] (ID_CATALOGO, CODIGO_CATALOGO, DESCRIPCION_CATALOGO, ACTIVO, ELIMINADO, FECHA_CREACION, USUARIO_CREACION, IP_CREACION) values(3, 23, 'Tipo de institución educativa', 1, 0, GETDATE(), 'ADMIN', 'SISTEMAS')
insert into [dbo].[catalogo] (ID_CATALOGO, CODIGO_CATALOGO, DESCRIPCION_CATALOGO, ACTIVO, ELIMINADO, FECHA_CREACION, USUARIO_CREACION, IP_CREACION) values(4, 5, 'Tipo de gestión de institución educativa', 1, 0, GETDATE(), 'ADMIN', 'SISTEMAS')
insert into [dbo].[catalogo] (ID_CATALOGO, CODIGO_CATALOGO, DESCRIPCION_CATALOGO, ACTIVO, ELIMINADO, FECHA_CREACION, USUARIO_CREACION, IP_CREACION) values(5, 24, 'Dependencia de institución educativa', 1, 0, GETDATE(), 'ADMIN', 'SISTEMAS')
insert into [dbo].[catalogo] (ID_CATALOGO, CODIGO_CATALOGO, DESCRIPCION_CATALOGO, ACTIVO, ELIMINADO, FECHA_CREACION, USUARIO_CREACION, IP_CREACION) values(6, 31, 'Pliego unidad ejecutora', 1, 0, GETDATE(), 'ADMIN', 'SISTEMAS')
insert into [dbo].[catalogo] (ID_CATALOGO, CODIGO_CATALOGO, DESCRIPCION_CATALOGO, ACTIVO, ELIMINADO, FECHA_CREACION, USUARIO_CREACION, IP_CREACION) values(7, 11, 'Situación laboral', 1, 0, GETDATE(), 'ADMIN', 'SISTEMAS')
insert into [dbo].[catalogo] (ID_CATALOGO, CODIGO_CATALOGO, DESCRIPCION_CATALOGO, ACTIVO, ELIMINADO, FECHA_CREACION, USUARIO_CREACION, IP_CREACION) values(8, 13, 'Condición laboral', 1, 0, GETDATE(), 'ADMIN', 'SISTEMAS')
insert into [dbo].[catalogo] (ID_CATALOGO, CODIGO_CATALOGO, DESCRIPCION_CATALOGO, ACTIVO, ELIMINADO, FECHA_CREACION, USUARIO_CREACION, IP_CREACION) values(9, 19, 'Estado civil de persona', 1, 0, GETDATE(), 'ADMIN', 'SISTEMAS')
insert into [dbo].[catalogo] (ID_CATALOGO, CODIGO_CATALOGO, DESCRIPCION_CATALOGO, ACTIVO, ELIMINADO, FECHA_CREACION, USUARIO_CREACION, IP_CREACION) values(10, 32, 'Género de persona', 1, 0, GETDATE(), 'ADMIN', 'SISTEMAS')
insert into [dbo].[catalogo] (ID_CATALOGO, CODIGO_CATALOGO, DESCRIPCION_CATALOGO, ACTIVO, ELIMINADO, FECHA_CREACION, USUARIO_CREACION, IP_CREACION) values(11, 57, 'Grupo carrera de formación académica', 1, 0, GETDATE(), 'ADMIN', 'SISTEMAS')
insert into [dbo].[catalogo] (ID_CATALOGO, CODIGO_CATALOGO, DESCRIPCION_CATALOGO, ACTIVO, ELIMINADO, FECHA_CREACION, USUARIO_CREACION, IP_CREACION) values(12, 58, 'Nivel carrera de formación académica', 1, 0, GETDATE(), 'ADMIN', 'SISTEMAS')
insert into [dbo].[catalogo] (ID_CATALOGO, CODIGO_CATALOGO, DESCRIPCION_CATALOGO, ACTIVO, ELIMINADO, FECHA_CREACION, USUARIO_CREACION, IP_CREACION) values(13, 59, 'Colegio profesional de formación académica', 1, 0, GETDATE(), 'ADMIN', 'SISTEMAS')
insert into [dbo].[catalogo] (ID_CATALOGO, CODIGO_CATALOGO, DESCRIPCION_CATALOGO, ACTIVO, ELIMINADO, FECHA_CREACION, USUARIO_CREACION, IP_CREACION) values(14, 60, 'Situación académica de formación académica', 1, 0, GETDATE(), 'ADMIN', 'SISTEMAS')
insert into [dbo].[catalogo] (ID_CATALOGO, CODIGO_CATALOGO, DESCRIPCION_CATALOGO, ACTIVO, ELIMINADO, FECHA_CREACION, USUARIO_CREACION, IP_CREACION) values(15, 61, 'Nivel del centro de estudio', 1, 0, GETDATE(), 'ADMIN', 'SISTEMAS')
insert into [dbo].[catalogo] (ID_CATALOGO, CODIGO_CATALOGO, DESCRIPCION_CATALOGO, ACTIVO, ELIMINADO, FECHA_CREACION, USUARIO_CREACION, IP_CREACION) values(16, 68, 'Tipo Retención tributaria', 1, 0, GETDATE(), 'ADMIN', 'SISTEMAS')
insert into [dbo].[catalogo] (ID_CATALOGO, CODIGO_CATALOGO, DESCRIPCION_CATALOGO, ACTIVO, ELIMINADO, FECHA_CREACION, USUARIO_CREACION, IP_CREACION) values(17, 69, 'Tipo de comisión AFP', 1, 0, GETDATE(), 'ADMIN', 'SISTEMAS')
insert into [dbo].[catalogo] (ID_CATALOGO, CODIGO_CATALOGO, DESCRIPCION_CATALOGO, ACTIVO, ELIMINADO, FECHA_CREACION, USUARIO_CREACION, IP_CREACION) values(18, 70, 'Tipo de Jornada laboral', 1, 0, GETDATE(), 'ADMIN', 'SISTEMAS')
insert into [dbo].[catalogo] (ID_CATALOGO, CODIGO_CATALOGO, DESCRIPCION_CATALOGO, ACTIVO, ELIMINADO, FECHA_CREACION, USUARIO_CREACION, IP_CREACION) values(19, 16, 'Tipo de persona', 1, 0, GETDATE(), 'ADMIN', 'SISTEMAS')
ALTER SEQUENCE dbo.seq_catalogo RESTART WITH 20;


GO