USE [db_ayni_personal_servidorpublico]
GO

insert into [dbo].[regimen_pensionario] (ID_REGIMEN_PENSIONARIO, ID_TIPO_RETENCION_TRIBUTARIA, CODIGO_REGIMEN_PENSIONARIO, DESCRIPCION_REGIMEN_PENSIONARIO, ACTIVO, FECHA_CREACION, USUARIO_CREACION, IP_CREACION) values(NEXT VALUE FOR [dbo].[seq_regimen_pensionario], 227, 13, 'DECRETO LEY 20530 - REGIMEN DE PENSIONES', 1, GETDATE(), 'ADMIN', 'SISTEMAS')
insert into [dbo].[regimen_pensionario] (ID_REGIMEN_PENSIONARIO, ID_TIPO_RETENCION_TRIBUTARIA, CODIGO_REGIMEN_PENSIONARIO, DESCRIPCION_REGIMEN_PENSIONARIO, ACTIVO, FECHA_CREACION, USUARIO_CREACION, IP_CREACION) values(NEXT VALUE FOR [dbo].[seq_regimen_pensionario], 227, 15, 'DECRETO LEY 25897 - SISTEMA PRIVADO DE PENSIONES', 1, GETDATE(), 'ADMIN', 'SISTEMAS')
insert into [dbo].[regimen_pensionario] (ID_REGIMEN_PENSIONARIO, ID_TIPO_RETENCION_TRIBUTARIA, CODIGO_REGIMEN_PENSIONARIO, DESCRIPCION_REGIMEN_PENSIONARIO, ACTIVO, FECHA_CREACION, USUARIO_CREACION, IP_CREACION) values(NEXT VALUE FOR [dbo].[seq_regimen_pensionario], 227, 16, 'DECRETO LEY 19990 - SISTEMA NACIONAL DE PENSIONES', 1, GETDATE(), 'ADMIN', 'SISTEMAS')
insert into [dbo].[regimen_pensionario] (ID_REGIMEN_PENSIONARIO, ID_TIPO_RETENCION_TRIBUTARIA, CODIGO_REGIMEN_PENSIONARIO, DESCRIPCION_REGIMEN_PENSIONARIO, ACTIVO, FECHA_CREACION, USUARIO_CREACION, IP_CREACION) values(NEXT VALUE FOR [dbo].[seq_regimen_pensionario], 227, 21, 'BENEFICIARIO JUDICIAL - DE PENSIONISTA', 1, GETDATE(), 'ADMIN', 'SISTEMAS')

GO