USE [db_ayni_personal_servidorpublico]
GO

insert into [dbo].[afp] (ID_AFP, ID_REGIMEN_PENSIONARIO, CODIGO_AFP, DESCRIPCION_AFP, ABREVIATURA_AFP_SUNAT, ACTIVO, FECHA_CREACION, USUARIO_CREACION, IP_CREACION) values(NEXT VALUE FOR dbo.seq_afp, 2, 1, 'HORIZONTE', '', 0, GETDATE(), 'ADMIN', 'SISTEMAS')
insert into [dbo].[afp] (ID_AFP, ID_REGIMEN_PENSIONARIO, CODIGO_AFP, DESCRIPCION_AFP, ABREVIATURA_AFP_SUNAT, ACTIVO, FECHA_CREACION, USUARIO_CREACION, IP_CREACION) values(NEXT VALUE FOR dbo.seq_afp, 2, 2, 'INTEGRA', '', 1, GETDATE(), 'ADMIN', 'SISTEMAS')
insert into [dbo].[afp] (ID_AFP, ID_REGIMEN_PENSIONARIO, CODIGO_AFP, DESCRIPCION_AFP, ABREVIATURA_AFP_SUNAT, ACTIVO, FECHA_CREACION, USUARIO_CREACION, IP_CREACION) values(NEXT VALUE FOR dbo.seq_afp, 2, 3, 'UNION VIDA', '', 0, GETDATE(), 'ADMIN', 'SISTEMAS')
insert into [dbo].[afp] (ID_AFP, ID_REGIMEN_PENSIONARIO, CODIGO_AFP, DESCRIPCION_AFP, ABREVIATURA_AFP_SUNAT, ACTIVO, FECHA_CREACION, USUARIO_CREACION, IP_CREACION) values(NEXT VALUE FOR dbo.seq_afp, 2, 4, 'PROFUTURO', '', 1, GETDATE(), 'ADMIN', 'SISTEMAS')
insert into [dbo].[afp] (ID_AFP, ID_REGIMEN_PENSIONARIO, CODIGO_AFP, DESCRIPCION_AFP, ABREVIATURA_AFP_SUNAT, ACTIVO, FECHA_CREACION, USUARIO_CREACION, IP_CREACION) values(NEXT VALUE FOR dbo.seq_afp, 2, 5, 'PRIMA', '', 1, GETDATE(), 'ADMIN', 'SISTEMAS')
insert into [dbo].[afp] (ID_AFP, ID_REGIMEN_PENSIONARIO, CODIGO_AFP, DESCRIPCION_AFP, ABREVIATURA_AFP_SUNAT, ACTIVO, FECHA_CREACION, USUARIO_CREACION, IP_CREACION) values(NEXT VALUE FOR dbo.seq_afp, 2, 6, 'HABITAT', '', 1, GETDATE(), 'ADMIN', 'SISTEMAS')
insert into [dbo].[afp] (ID_AFP, ID_REGIMEN_PENSIONARIO, CODIGO_AFP, DESCRIPCION_AFP, ABREVIATURA_AFP_SUNAT, ACTIVO, FECHA_CREACION, USUARIO_CREACION, IP_CREACION) values(NEXT VALUE FOR dbo.seq_afp, 2, 7, 'N/A', '', 0, GETDATE(), 'ADMIN', 'SISTEMAS')
insert into [dbo].[afp] (ID_AFP, ID_REGIMEN_PENSIONARIO, CODIGO_AFP, DESCRIPCION_AFP, ABREVIATURA_AFP_SUNAT, ACTIVO, FECHA_CREACION, USUARIO_CREACION, IP_CREACION) values(NEXT VALUE FOR dbo.seq_afp, 2, 8, 'EL ROBLE', '', 0, GETDATE(), 'ADMIN', 'SISTEMAS')
insert into [dbo].[afp] (ID_AFP, ID_REGIMEN_PENSIONARIO, CODIGO_AFP, DESCRIPCION_AFP, ABREVIATURA_AFP_SUNAT, ACTIVO, FECHA_CREACION, USUARIO_CREACION, IP_CREACION) values(NEXT VALUE FOR dbo.seq_afp, 2, 9, 'NUEVA VIDA', '', 0, GETDATE(), 'ADMIN', 'SISTEMAS')

GO