USE [db_ayni_personal_servidorpublico]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[regimen_laboral_temp]') AND type in (N'U'))
DROP TABLE [dbo].[regimen_laboral_temp]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[regimen_laboral_temp](
	[ID_REGIMEN_LABORAL] [int] NOT NULL,
	[ID_TIPO_RETENCION_TRIBUTARIA] [int] NULL,
	[CODIGO_REGIMEN_LABORAL] [int] NOT NULL,
	[DESCRIPCION_REGIMEN_LABORAL] [varchar](200) NOT NULL,
	[ABREVIATURA_REGIMEN_LABORAL] [varchar](30) NOT NULL,
	[ADMINISTRATIVO] [bit] NOT NULL,
	[FECHA_INICIO_VIGENCIA] [datetime] NOT NULL,
	[FECHA_FIN_VIGENCIA] [datetime] NULL,
	[ACTIVO] [bit] NOT NULL,
	[FECHA_CREACION] [datetime] NOT NULL,
	[USUARIO_CREACION] [varchar](20) NOT NULL,
	[IP_CREACION] [varchar](40) NOT NULL,
	[FECHA_MODIFICACION] [datetime] NULL,
	[USUARIO_MODIFICACION] [varchar](20) NULL,
	[IP_MODIFICACION] [varchar](40) NULL
) ON [PRIMARY]
GO
INSERT [dbo].[regimen_laboral_temp] ([ID_REGIMEN_LABORAL], [ID_TIPO_RETENCION_TRIBUTARIA], [CODIGO_REGIMEN_LABORAL], [DESCRIPCION_REGIMEN_LABORAL], [ABREVIATURA_REGIMEN_LABORAL], [ADMINISTRATIVO], [FECHA_INICIO_VIGENCIA], [FECHA_FIN_VIGENCIA], [ACTIVO], [FECHA_CREACION], [USUARIO_CREACION], [IP_CREACION], [FECHA_MODIFICACION], [USUARIO_MODIFICACION], [IP_MODIFICACION]) VALUES (1, 226, 1, N'LEY 29944 - LEY DE REFORMA MAGISTERIAL', N'LEY 29944-LRM', 0, CAST(N'2012-11-26T00:00:00.000' AS DateTime), NULL, 1, CAST(N'2021-07-16T12:39:27.740' AS DateTime), N'ADMIN', N'SISTEMAS', NULL, NULL, NULL)
INSERT [dbo].[regimen_laboral_temp] ([ID_REGIMEN_LABORAL], [ID_TIPO_RETENCION_TRIBUTARIA], [CODIGO_REGIMEN_LABORAL], [DESCRIPCION_REGIMEN_LABORAL], [ABREVIATURA_REGIMEN_LABORAL], [ADMINISTRATIVO], [FECHA_INICIO_VIGENCIA], [FECHA_FIN_VIGENCIA], [ACTIVO], [FECHA_CREACION], [USUARIO_CREACION], [IP_CREACION], [FECHA_MODIFICACION], [USUARIO_MODIFICACION], [IP_MODIFICACION]) VALUES (2, 226, 2, N'LEY 30512 - EDUCACION SUPERIOR NO UNIVERSITARIA NOMBRADOS', N'LEY 30512-ESNU NOMBRADO', 0, CAST(N'2016-11-02T00:00:00.000' AS DateTime), NULL, 1, CAST(N'2021-07-16T12:39:27.743' AS DateTime), N'ADMIN', N'SISTEMAS', NULL, NULL, NULL)
INSERT [dbo].[regimen_laboral_temp] ([ID_REGIMEN_LABORAL], [ID_TIPO_RETENCION_TRIBUTARIA], [CODIGO_REGIMEN_LABORAL], [DESCRIPCION_REGIMEN_LABORAL], [ABREVIATURA_REGIMEN_LABORAL], [ADMINISTRATIVO], [FECHA_INICIO_VIGENCIA], [FECHA_FIN_VIGENCIA], [ACTIVO], [FECHA_CREACION], [USUARIO_CREACION], [IP_CREACION], [FECHA_MODIFICACION], [USUARIO_MODIFICACION], [IP_MODIFICACION]) VALUES (3, 226, 3, N'LEY 30328 - CONTRATO DE SERVICIO DOCENTE', N'LEY 30328-DOC. CONTRATADO', 0, CAST(N'2017-03-01T00:00:00.000' AS DateTime), NULL, 1, CAST(N'2021-07-16T12:39:27.743' AS DateTime), N'ADMIN', N'SISTEMAS', NULL, NULL, NULL)
INSERT [dbo].[regimen_laboral_temp] ([ID_REGIMEN_LABORAL], [ID_TIPO_RETENCION_TRIBUTARIA], [CODIGO_REGIMEN_LABORAL], [DESCRIPCION_REGIMEN_LABORAL], [ABREVIATURA_REGIMEN_LABORAL], [ADMINISTRATIVO], [FECHA_INICIO_VIGENCIA], [FECHA_FIN_VIGENCIA], [ACTIVO], [FECHA_CREACION], [USUARIO_CREACION], [IP_CREACION], [FECHA_MODIFICACION], [USUARIO_MODIFICACION], [IP_MODIFICACION]) VALUES (4, 226, 4, N'LEY 30493 - AUXILIAR EDUCACIÓN', N'LEY 30493-AUX. EDUCACION', 0, CAST(N'2017-03-01T00:00:00.000' AS DateTime), NULL, 1, CAST(N'2021-07-16T12:39:27.747' AS DateTime), N'ADMIN', N'SISTEMAS', NULL, NULL, NULL)
INSERT [dbo].[regimen_laboral_temp] ([ID_REGIMEN_LABORAL], [ID_TIPO_RETENCION_TRIBUTARIA], [CODIGO_REGIMEN_LABORAL], [DESCRIPCION_REGIMEN_LABORAL], [ABREVIATURA_REGIMEN_LABORAL], [ADMINISTRATIVO], [FECHA_INICIO_VIGENCIA], [FECHA_FIN_VIGENCIA], [ACTIVO], [FECHA_CREACION], [USUARIO_CREACION], [IP_CREACION], [FECHA_MODIFICACION], [USUARIO_MODIFICACION], [IP_MODIFICACION]) VALUES (5, 226, 6, N'DECRETO LEGISLATIVO 276 - CARRERA ADMINISTRATIVA', N'D.LEG. 276-ADMIN', 1, CAST(N'1984-03-06T00:00:00.000' AS DateTime), NULL, 1, CAST(N'2021-07-16T12:39:27.747' AS DateTime), N'ADMIN', N'SISTEMAS', NULL, NULL, NULL)
INSERT [dbo].[regimen_laboral_temp] ([ID_REGIMEN_LABORAL], [ID_TIPO_RETENCION_TRIBUTARIA], [CODIGO_REGIMEN_LABORAL], [DESCRIPCION_REGIMEN_LABORAL], [ABREVIATURA_REGIMEN_LABORAL], [ADMINISTRATIVO], [FECHA_INICIO_VIGENCIA], [FECHA_FIN_VIGENCIA], [ACTIVO], [FECHA_CREACION], [USUARIO_CREACION], [IP_CREACION], [FECHA_MODIFICACION], [USUARIO_MODIFICACION], [IP_MODIFICACION]) VALUES (6, 226, 7, N'DECRETO LEGISLATIVO 1153 - PROFESIONALES DE LA SALUD', N'D.LEG. 1153-PROSAL', 1, CAST(N'2013-09-12T00:00:00.000' AS DateTime), NULL, 1, CAST(N'2021-07-16T12:39:27.747' AS DateTime), N'ADMIN', N'SISTEMAS', NULL, NULL, NULL)
INSERT [dbo].[regimen_laboral_temp] ([ID_REGIMEN_LABORAL], [ID_TIPO_RETENCION_TRIBUTARIA], [CODIGO_REGIMEN_LABORAL], [DESCRIPCION_REGIMEN_LABORAL], [ABREVIATURA_REGIMEN_LABORAL], [ADMINISTRATIVO], [FECHA_INICIO_VIGENCIA], [FECHA_FIN_VIGENCIA], [ACTIVO], [FECHA_CREACION], [USUARIO_CREACION], [IP_CREACION], [FECHA_MODIFICACION], [USUARIO_MODIFICACION], [IP_MODIFICACION]) VALUES (7, 226, 8, N'DECRETO LEGISLATIVO 728 - REGIMEN PRIVADO', N'D.LEG. 728', 1, CAST(N'1993-01-01T00:00:00.000' AS DateTime), NULL, 1, CAST(N'2021-07-16T12:39:27.747' AS DateTime), N'ADMIN', N'SISTEMAS', NULL, NULL, NULL)
INSERT [dbo].[regimen_laboral_temp] ([ID_REGIMEN_LABORAL], [ID_TIPO_RETENCION_TRIBUTARIA], [CODIGO_REGIMEN_LABORAL], [DESCRIPCION_REGIMEN_LABORAL], [ABREVIATURA_REGIMEN_LABORAL], [ADMINISTRATIVO], [FECHA_INICIO_VIGENCIA], [FECHA_FIN_VIGENCIA], [ACTIVO], [FECHA_CREACION], [USUARIO_CREACION], [IP_CREACION], [FECHA_MODIFICACION], [USUARIO_MODIFICACION], [IP_MODIFICACION]) VALUES (8, 225, 9, N'DECRETO LEGISLATIVO 1057 - CONTRATACIÓN ADMINISTRATIVA DE SERVICIO', N'D.LEG. 1057-CAS', 1, CAST(N'2008-06-28T00:00:00.000' AS DateTime), NULL, 1, CAST(N'2021-07-16T12:39:27.750' AS DateTime), N'ADMIN', N'SISTEMAS', NULL, NULL, NULL)
INSERT [dbo].[regimen_laboral_temp] ([ID_REGIMEN_LABORAL], [ID_TIPO_RETENCION_TRIBUTARIA], [CODIGO_REGIMEN_LABORAL], [DESCRIPCION_REGIMEN_LABORAL], [ABREVIATURA_REGIMEN_LABORAL], [ADMINISTRATIVO], [FECHA_INICIO_VIGENCIA], [FECHA_FIN_VIGENCIA], [ACTIVO], [FECHA_CREACION], [USUARIO_CREACION], [IP_CREACION], [FECHA_MODIFICACION], [USUARIO_MODIFICACION], [IP_MODIFICACION]) VALUES (9, 226, 10, N'LEY 30057 - SERVICIO CIVIL - SERVIR', N'LEY 30057-SERVIR', 1, CAST(N'2013-07-04T00:00:00.000' AS DateTime), NULL, 1, CAST(N'2021-07-16T12:39:27.750' AS DateTime), N'ADMIN', N'SISTEMAS', NULL, NULL, NULL)
INSERT [dbo].[regimen_laboral_temp] ([ID_REGIMEN_LABORAL], [ID_TIPO_RETENCION_TRIBUTARIA], [CODIGO_REGIMEN_LABORAL], [DESCRIPCION_REGIMEN_LABORAL], [ABREVIATURA_REGIMEN_LABORAL], [ADMINISTRATIVO], [FECHA_INICIO_VIGENCIA], [FECHA_FIN_VIGENCIA], [ACTIVO], [FECHA_CREACION], [USUARIO_CREACION], [IP_CREACION], [FECHA_MODIFICACION], [USUARIO_MODIFICACION], [IP_MODIFICACION]) VALUES (10, 226, 11, N'LEY 24029 - LEY DEL PROFESORADO', N'LEY 24029', 0, CAST(N'1984-12-14T00:00:00.000' AS DateTime), CAST(N'2016-11-01T00:00:00.000' AS DateTime), 0, CAST(N'2021-07-16T12:39:27.750' AS DateTime), N'ADMIN', N'SISTEMAS', NULL, NULL, NULL)
INSERT [dbo].[regimen_laboral_temp] ([ID_REGIMEN_LABORAL], [ID_TIPO_RETENCION_TRIBUTARIA], [CODIGO_REGIMEN_LABORAL], [DESCRIPCION_REGIMEN_LABORAL], [ABREVIATURA_REGIMEN_LABORAL], [ADMINISTRATIVO], [FECHA_INICIO_VIGENCIA], [FECHA_FIN_VIGENCIA], [ACTIVO], [FECHA_CREACION], [USUARIO_CREACION], [IP_CREACION], [FECHA_MODIFICACION], [USUARIO_MODIFICACION], [IP_MODIFICACION]) VALUES (11, 226, 12, N'LEY 29062 - LEY DE LA CARRERA PUBLICA MAGISTERIAL', N'LEY 29062', 0, CAST(N'2007-07-12T00:00:00.000' AS DateTime), CAST(N'2012-11-25T00:00:00.000' AS DateTime), 0, CAST(N'2021-07-16T12:39:27.750' AS DateTime), N'ADMIN', N'SISTEMAS', NULL, NULL, NULL)
INSERT [dbo].[regimen_laboral_temp] ([ID_REGIMEN_LABORAL], [ID_TIPO_RETENCION_TRIBUTARIA], [CODIGO_REGIMEN_LABORAL], [DESCRIPCION_REGIMEN_LABORAL], [ABREVIATURA_REGIMEN_LABORAL], [ADMINISTRATIVO], [FECHA_INICIO_VIGENCIA], [FECHA_FIN_VIGENCIA], [ACTIVO], [FECHA_CREACION], [USUARIO_CREACION], [IP_CREACION], [FECHA_MODIFICACION], [USUARIO_MODIFICACION], [IP_MODIFICACION]) VALUES (12, 226, 22, N'DECRETO LEGISLATIVO 559 - PROFESIONALES DE LA SALUD', N'DL 559', 0, CAST(N'2015-12-15T00:00:00.000' AS DateTime), NULL, 0, CAST(N'2021-07-16T12:39:27.753' AS DateTime), N'ADMIN', N'SISTEMAS', NULL, NULL, NULL)
INSERT [dbo].[regimen_laboral_temp] ([ID_REGIMEN_LABORAL], [ID_TIPO_RETENCION_TRIBUTARIA], [CODIGO_REGIMEN_LABORAL], [DESCRIPCION_REGIMEN_LABORAL], [ABREVIATURA_REGIMEN_LABORAL], [ADMINISTRATIVO], [FECHA_INICIO_VIGENCIA], [FECHA_FIN_VIGENCIA], [ACTIVO], [FECHA_CREACION], [USUARIO_CREACION], [IP_CREACION], [FECHA_MODIFICACION], [USUARIO_MODIFICACION], [IP_MODIFICACION]) VALUES (13, 226, 23, N'LEY 23536 - PROFESIONALES DE LA SALUD', N'LEY 23536-PS', 1, CAST(N'2016-06-06T00:00:00.000' AS DateTime), NULL, 0, CAST(N'2021-07-16T12:39:27.753' AS DateTime), N'ADMIN', N'SISTEMAS', NULL, NULL, NULL)
INSERT [dbo].[regimen_laboral_temp] ([ID_REGIMEN_LABORAL], [ID_TIPO_RETENCION_TRIBUTARIA], [CODIGO_REGIMEN_LABORAL], [DESCRIPCION_REGIMEN_LABORAL], [ABREVIATURA_REGIMEN_LABORAL], [ADMINISTRATIVO], [FECHA_INICIO_VIGENCIA], [FECHA_FIN_VIGENCIA], [ACTIVO], [FECHA_CREACION], [USUARIO_CREACION], [IP_CREACION], [FECHA_MODIFICACION], [USUARIO_MODIFICACION], [IP_MODIFICACION]) VALUES (14, 226, 24, N'LEY 30372 - EDUCACION SUPERIOR NO UNIVERSITARIA CONTRATADOS (95° DCF)', N'LEY 30372-ESNU CONTRATADO', 1, CAST(N'2016-12-28T00:00:00.000' AS DateTime), NULL, 0, CAST(N'2021-07-16T12:39:27.753' AS DateTime), N'ADMIN', N'SISTEMAS', NULL, NULL, NULL)
INSERT [dbo].[regimen_laboral_temp] ([ID_REGIMEN_LABORAL], [ID_TIPO_RETENCION_TRIBUTARIA], [CODIGO_REGIMEN_LABORAL], [DESCRIPCION_REGIMEN_LABORAL], [ABREVIATURA_REGIMEN_LABORAL], [ADMINISTRATIVO], [FECHA_INICIO_VIGENCIA], [FECHA_FIN_VIGENCIA], [ACTIVO], [FECHA_CREACION], [USUARIO_CREACION], [IP_CREACION], [FECHA_MODIFICACION], [USUARIO_MODIFICACION], [IP_MODIFICACION]) VALUES (15, NULL, 26, N'DECRETO LEGISLATIVO 1024', N'D.LEG. 1024', 1, CAST(N'2020-05-04T00:00:00.000' AS DateTime), NULL, 1, CAST(N'2021-07-16T12:39:27.757' AS DateTime), N'ADMIN', N'SISTEMAS', NULL, NULL, NULL)
INSERT [dbo].[regimen_laboral_temp] ([ID_REGIMEN_LABORAL], [ID_TIPO_RETENCION_TRIBUTARIA], [CODIGO_REGIMEN_LABORAL], [DESCRIPCION_REGIMEN_LABORAL], [ABREVIATURA_REGIMEN_LABORAL], [ADMINISTRATIVO], [FECHA_INICIO_VIGENCIA], [FECHA_FIN_VIGENCIA], [ACTIVO], [FECHA_CREACION], [USUARIO_CREACION], [IP_CREACION], [FECHA_MODIFICACION], [USUARIO_MODIFICACION], [IP_MODIFICACION]) VALUES (16, NULL, 900, N'SIN RÉGIMEN', N'SIN RÉGIMEN', 1, CAST(N'2021-07-16T12:39:27.757' AS DateTime), NULL, 1, CAST(N'2021-07-16T12:39:27.757' AS DateTime), N'ADMIN', N'SISTEMAS', NULL, NULL, NULL)
INSERT [dbo].[regimen_laboral_temp] ([ID_REGIMEN_LABORAL], [ID_TIPO_RETENCION_TRIBUTARIA], [CODIGO_REGIMEN_LABORAL], [DESCRIPCION_REGIMEN_LABORAL], [ABREVIATURA_REGIMEN_LABORAL], [ADMINISTRATIVO], [FECHA_INICIO_VIGENCIA], [FECHA_FIN_VIGENCIA], [ACTIVO], [FECHA_CREACION], [USUARIO_CREACION], [IP_CREACION], [FECHA_MODIFICACION], [USUARIO_MODIFICACION], [IP_MODIFICACION]) VALUES (17, NULL, 902, N'MÚLTIPLE', N'MÚLTIPLE', 1, CAST(N'2021-07-16T12:39:27.757' AS DateTime), NULL, 1, CAST(N'2021-07-16T12:39:27.757' AS DateTime), N'ADMIN', N'SISTEMAS', NULL, NULL, NULL)
INSERT [dbo].[regimen_laboral_temp] ([ID_REGIMEN_LABORAL], [ID_TIPO_RETENCION_TRIBUTARIA], [CODIGO_REGIMEN_LABORAL], [DESCRIPCION_REGIMEN_LABORAL], [ABREVIATURA_REGIMEN_LABORAL], [ADMINISTRATIVO], [FECHA_INICIO_VIGENCIA], [FECHA_FIN_VIGENCIA], [ACTIVO], [FECHA_CREACION], [USUARIO_CREACION], [IP_CREACION], [FECHA_MODIFICACION], [USUARIO_MODIFICACION], [IP_MODIFICACION]) VALUES (18, NULL, 27, N'DECRETO LEY 20530 - RÉGIMEN DE PENSIONES', N'LEY 20530-PENSIONES', 1, CAST(N'2021-07-16T12:39:27.757' AS DateTime), NULL, 1, CAST(N'2021-07-16T12:39:27.757' AS DateTime), N'ADMIN', N'SISTEMAS', NULL, NULL, NULL)
INSERT [dbo].[regimen_laboral_temp] ([ID_REGIMEN_LABORAL], [ID_TIPO_RETENCION_TRIBUTARIA], [CODIGO_REGIMEN_LABORAL], [DESCRIPCION_REGIMEN_LABORAL], [ABREVIATURA_REGIMEN_LABORAL], [ADMINISTRATIVO], [FECHA_INICIO_VIGENCIA], [FECHA_FIN_VIGENCIA], [ACTIVO], [FECHA_CREACION], [USUARIO_CREACION], [IP_CREACION], [FECHA_MODIFICACION], [USUARIO_MODIFICACION], [IP_MODIFICACION]) VALUES (19, NULL, 28, N'DECRETO LEY 11192 - PALMAS MAGISTERIALES', N'LEY 11192-PALMAS M.', 1, CAST(N'2021-07-16T12:39:27.760' AS DateTime), NULL, 1, CAST(N'2021-07-16T12:39:27.760' AS DateTime), N'ADMIN', N'SISTEMAS', NULL, NULL, NULL)
INSERT [dbo].[regimen_laboral_temp] ([ID_REGIMEN_LABORAL], [ID_TIPO_RETENCION_TRIBUTARIA], [CODIGO_REGIMEN_LABORAL], [DESCRIPCION_REGIMEN_LABORAL], [ABREVIATURA_REGIMEN_LABORAL], [ADMINISTRATIVO], [FECHA_INICIO_VIGENCIA], [FECHA_FIN_VIGENCIA], [ACTIVO], [FECHA_CREACION], [USUARIO_CREACION], [IP_CREACION], [FECHA_MODIFICACION], [USUARIO_MODIFICACION], [IP_MODIFICACION]) VALUES (20, NULL, 29, N'LEY 29029 - LEY DE LA MANCOMUNIDAD MUNICIPAL', N'LEY 29029', 1, CAST(N'2021-07-16T12:39:27.760' AS DateTime), NULL, 1, CAST(N'2021-07-16T12:39:27.760' AS DateTime), N'ADMIN', N'SISTEMAS', NULL, NULL, NULL)
GO


--- Actualizacion de regimen_laboral
update  ca
SET 
	ca.ID_REGIMEN_LABORAL = c.ID_REGIMEN_LABORAL,
	ca.ID_TIPO_RETENCION_TRIBUTARIA = c.ID_TIPO_RETENCION_TRIBUTARIA, 
	ca.CODIGO_REGIMEN_LABORAL = c.CODIGO_REGIMEN_LABORAL,
	ca.DESCRIPCION_REGIMEN_LABORAL = c.DESCRIPCION_REGIMEN_LABORAL,
	ca.ABREVIATURA_REGIMEN_LABORAL = c.ABREVIATURA_REGIMEN_LABORAL,
	ca.ADMINISTRATIVO = c.ADMINISTRATIVO,
	ca.FECHA_INICIO_VIGENCIA =  c.FECHA_INICIO_VIGENCIA,
	ca.FECHA_FIN_VIGENCIA = c.FECHA_FIN_VIGENCIA,
	ca.ACTIVO = c.ACTIVO
from regimen_laboral_temp  c inner join regimen_laboral ca  on c.ID_REGIMEN_LABORAL = ca.ID_REGIMEN_LABORAL

GO
--- Insertamos nuevos regimen_laboral
insert into regimen_laboral
SELECT 
c.*
from regimen_laboral_temp  c left join regimen_laboral ca  on c.ID_REGIMEN_LABORAL=ca.ID_REGIMEN_LABORAL
where 
  ca.ID_REGIMEN_LABORAL is null

GO
-- eliminamos tabla temporal

drop table regimen_laboral_temp

----
GO

alter sequence seq_regimen_laboral restart with 21;





