USE [db_ayni_personal_servidorpublico]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[nivel_educativo_temp]') AND type in (N'U'))
DROP TABLE [dbo].[nivel_educativo_temp]
GO
create table dbo.nivel_educativo_temp (
   ID_NIVEL_EDUCATIVO   int                  not null,
   ID_MODALIDAD_EDUCATIVA int                  null,
   CODIGO_NIVEL_EDUCATIVO varchar(4)           not null,
   DESCRIPCION_NIVEL_EDUCATIVO varchar(50)          not null,
   ABREVIATURA_NIVEL_EDUCATIVO varchar(10)          null,
   ORDEN                int                  null,
   ACTIVO               bit                  not null,
   FECHA_CREACION       datetime             not null,
   USUARIO_CREACION     varchar(20)          not null,
   IP_CREACION          varchar(40)          not null,
   FECHA_MODIFICACION   datetime             null,
   USUARIO_MODIFICACION varchar(20)          null,
   IP_MODIFICACION      varchar(40)          null,
   constraint PK_NIVEL_EDUCATIVO_TEMP primary key (ID_NIVEL_EDUCATIVO)
)
go

INSERT [dbo].[nivel_educativo_temp] ([ID_NIVEL_EDUCATIVO], [ID_MODALIDAD_EDUCATIVA], [CODIGO_NIVEL_EDUCATIVO], [DESCRIPCION_NIVEL_EDUCATIVO], [ABREVIATURA_NIVEL_EDUCATIVO], [ORDEN], [ACTIVO], [FECHA_CREACION], [USUARIO_CREACION], [IP_CREACION], [FECHA_MODIFICACION], [USUARIO_MODIFICACION], [IP_MODIFICACION]) VALUES (1, 1, N'1', N'EBR - INICIAL - CUNA', N'', NULL, 1, CAST(N'2021-07-20T12:13:14.417' AS DateTime), N'ADMIN', N'SISTEMAS', NULL, NULL, NULL)
INSERT [dbo].[nivel_educativo_temp] ([ID_NIVEL_EDUCATIVO], [ID_MODALIDAD_EDUCATIVA], [CODIGO_NIVEL_EDUCATIVO], [DESCRIPCION_NIVEL_EDUCATIVO], [ABREVIATURA_NIVEL_EDUCATIVO], [ORDEN], [ACTIVO], [FECHA_CREACION], [USUARIO_CREACION], [IP_CREACION], [FECHA_MODIFICACION], [USUARIO_MODIFICACION], [IP_MODIFICACION]) VALUES (2, 1, N'2', N'EBR - INICIAL - JARDÍN', N'', NULL, 1, CAST(N'2021-07-20T12:13:14.417' AS DateTime), N'ADMIN', N'SISTEMAS', NULL, NULL, NULL)
INSERT [dbo].[nivel_educativo_temp] ([ID_NIVEL_EDUCATIVO], [ID_MODALIDAD_EDUCATIVA], [CODIGO_NIVEL_EDUCATIVO], [DESCRIPCION_NIVEL_EDUCATIVO], [ABREVIATURA_NIVEL_EDUCATIVO], [ORDEN], [ACTIVO], [FECHA_CREACION], [USUARIO_CREACION], [IP_CREACION], [FECHA_MODIFICACION], [USUARIO_MODIFICACION], [IP_MODIFICACION]) VALUES (3, 1, N'3', N'EBR - INICIAL - CUNA - JARDÍN', N'', NULL, 1, CAST(N'2021-07-20T12:13:14.417' AS DateTime), N'ADMIN', N'SISTEMAS', NULL, NULL, NULL)
INSERT [dbo].[nivel_educativo_temp] ([ID_NIVEL_EDUCATIVO], [ID_MODALIDAD_EDUCATIVA], [CODIGO_NIVEL_EDUCATIVO], [DESCRIPCION_NIVEL_EDUCATIVO], [ABREVIATURA_NIVEL_EDUCATIVO], [ORDEN], [ACTIVO], [FECHA_CREACION], [USUARIO_CREACION], [IP_CREACION], [FECHA_MODIFICACION], [USUARIO_MODIFICACION], [IP_MODIFICACION]) VALUES (4, 3, N'4', N'EBE - INICIAL', N'', NULL, 1, CAST(N'2021-07-20T12:13:14.420' AS DateTime), N'ADMIN', N'SISTEMAS', NULL, NULL, NULL)
INSERT [dbo].[nivel_educativo_temp] ([ID_NIVEL_EDUCATIVO], [ID_MODALIDAD_EDUCATIVA], [CODIGO_NIVEL_EDUCATIVO], [DESCRIPCION_NIVEL_EDUCATIVO], [ABREVIATURA_NIVEL_EDUCATIVO], [ORDEN], [ACTIVO], [FECHA_CREACION], [USUARIO_CREACION], [IP_CREACION], [FECHA_MODIFICACION], [USUARIO_MODIFICACION], [IP_MODIFICACION]) VALUES (5, 1, N'5', N'EBR - PRIMARIA', N'', NULL, 1, CAST(N'2021-07-20T12:13:14.420' AS DateTime), N'ADMIN', N'SISTEMAS', NULL, NULL, NULL)
INSERT [dbo].[nivel_educativo_temp] ([ID_NIVEL_EDUCATIVO], [ID_MODALIDAD_EDUCATIVA], [CODIGO_NIVEL_EDUCATIVO], [DESCRIPCION_NIVEL_EDUCATIVO], [ABREVIATURA_NIVEL_EDUCATIVO], [ORDEN], [ACTIVO], [FECHA_CREACION], [USUARIO_CREACION], [IP_CREACION], [FECHA_MODIFICACION], [USUARIO_MODIFICACION], [IP_MODIFICACION]) VALUES (6, 1, N'7', N'EBR - SECUNDARIA', N'', NULL, 1, CAST(N'2021-07-20T12:13:14.420' AS DateTime), N'ADMIN', N'SISTEMAS', NULL, NULL, NULL)
INSERT [dbo].[nivel_educativo_temp] ([ID_NIVEL_EDUCATIVO], [ID_MODALIDAD_EDUCATIVA], [CODIGO_NIVEL_EDUCATIVO], [DESCRIPCION_NIVEL_EDUCATIVO], [ABREVIATURA_NIVEL_EDUCATIVO], [ORDEN], [ACTIVO], [FECHA_CREACION], [USUARIO_CREACION], [IP_CREACION], [FECHA_MODIFICACION], [USUARIO_MODIFICACION], [IP_MODIFICACION]) VALUES (7, 4, N'9', N'EDUCACIÓN SUPERIOR PEDAGÓGICA - ISP', N'', NULL, 1, CAST(N'2021-07-20T12:13:14.420' AS DateTime), N'ADMIN', N'SISTEMAS', NULL, NULL, NULL)
INSERT [dbo].[nivel_educativo_temp] ([ID_NIVEL_EDUCATIVO], [ID_MODALIDAD_EDUCATIVA], [CODIGO_NIVEL_EDUCATIVO], [DESCRIPCION_NIVEL_EDUCATIVO], [ABREVIATURA_NIVEL_EDUCATIVO], [ORDEN], [ACTIVO], [FECHA_CREACION], [USUARIO_CREACION], [IP_CREACION], [FECHA_MODIFICACION], [USUARIO_MODIFICACION], [IP_MODIFICACION]) VALUES (8, 4, N'10', N'EDUCACIÓN SUPERIOR TECNOLÓGICA - IST', N'', NULL, 1, CAST(N'2021-07-20T12:13:14.420' AS DateTime), N'ADMIN', N'SISTEMAS', NULL, NULL, NULL)
INSERT [dbo].[nivel_educativo_temp] ([ID_NIVEL_EDUCATIVO], [ID_MODALIDAD_EDUCATIVA], [CODIGO_NIVEL_EDUCATIVO], [DESCRIPCION_NIVEL_EDUCATIVO], [ABREVIATURA_NIVEL_EDUCATIVO], [ORDEN], [ACTIVO], [FECHA_CREACION], [USUARIO_CREACION], [IP_CREACION], [FECHA_MODIFICACION], [USUARIO_MODIFICACION], [IP_MODIFICACION]) VALUES (9, 4, N'11', N'EDUCACIÓN SUPERIOR ARTÍSTICA - ESCUELAS', N'', NULL, 1, CAST(N'2021-07-20T12:13:14.420' AS DateTime), N'ADMIN', N'SISTEMAS', NULL, NULL, NULL)
INSERT [dbo].[nivel_educativo_temp] ([ID_NIVEL_EDUCATIVO], [ID_MODALIDAD_EDUCATIVA], [CODIGO_NIVEL_EDUCATIVO], [DESCRIPCION_NIVEL_EDUCATIVO], [ABREVIATURA_NIVEL_EDUCATIVO], [ORDEN], [ACTIVO], [FECHA_CREACION], [USUARIO_CREACION], [IP_CREACION], [FECHA_MODIFICACION], [USUARIO_MODIFICACION], [IP_MODIFICACION]) VALUES (10, 3, N'12', N'EBE - PRIMARIA', N'', NULL, 1, CAST(N'2021-07-20T12:13:14.420' AS DateTime), N'ADMIN', N'SISTEMAS', NULL, NULL, NULL)
INSERT [dbo].[nivel_educativo_temp] ([ID_NIVEL_EDUCATIVO], [ID_MODALIDAD_EDUCATIVA], [CODIGO_NIVEL_EDUCATIVO], [DESCRIPCION_NIVEL_EDUCATIVO], [ABREVIATURA_NIVEL_EDUCATIVO], [ORDEN], [ACTIVO], [FECHA_CREACION], [USUARIO_CREACION], [IP_CREACION], [FECHA_MODIFICACION], [USUARIO_MODIFICACION], [IP_MODIFICACION]) VALUES (11, 5, N'13', N'CETPRO', N'', NULL, 1, CAST(N'2021-07-20T12:13:14.420' AS DateTime), N'ADMIN', N'SISTEMAS', NULL, NULL, NULL)
INSERT [dbo].[nivel_educativo_temp] ([ID_NIVEL_EDUCATIVO], [ID_MODALIDAD_EDUCATIVA], [CODIGO_NIVEL_EDUCATIVO], [DESCRIPCION_NIVEL_EDUCATIVO], [ABREVIATURA_NIVEL_EDUCATIVO], [ORDEN], [ACTIVO], [FECHA_CREACION], [USUARIO_CREACION], [IP_CREACION], [FECHA_MODIFICACION], [USUARIO_MODIFICACION], [IP_MODIFICACION]) VALUES (12, 5, N'14', N'CEO INDUSTRIAL', N'', NULL, 1, CAST(N'2021-07-20T12:13:14.420' AS DateTime), N'ADMIN', N'SISTEMAS', NULL, NULL, NULL)
INSERT [dbo].[nivel_educativo_temp] ([ID_NIVEL_EDUCATIVO], [ID_MODALIDAD_EDUCATIVA], [CODIGO_NIVEL_EDUCATIVO], [DESCRIPCION_NIVEL_EDUCATIVO], [ABREVIATURA_NIVEL_EDUCATIVO], [ORDEN], [ACTIVO], [FECHA_CREACION], [USUARIO_CREACION], [IP_CREACION], [FECHA_MODIFICACION], [USUARIO_MODIFICACION], [IP_MODIFICACION]) VALUES (13, 5, N'15', N'CEO AGROPECUARIA', N'', NULL, 0, CAST(N'2021-07-20T12:13:14.420' AS DateTime), N'ADMIN', N'SISTEMAS', NULL, NULL, NULL)
INSERT [dbo].[nivel_educativo_temp] ([ID_NIVEL_EDUCATIVO], [ID_MODALIDAD_EDUCATIVA], [CODIGO_NIVEL_EDUCATIVO], [DESCRIPCION_NIVEL_EDUCATIVO], [ABREVIATURA_NIVEL_EDUCATIVO], [ORDEN], [ACTIVO], [FECHA_CREACION], [USUARIO_CREACION], [IP_CREACION], [FECHA_MODIFICACION], [USUARIO_MODIFICACION], [IP_MODIFICACION]) VALUES (14, 5, N'16', N'CEO ARTESANAL', N'', NULL, 0, CAST(N'2021-07-20T12:13:14.420' AS DateTime), N'ADMIN', N'SISTEMAS', NULL, NULL, NULL)
INSERT [dbo].[nivel_educativo_temp] ([ID_NIVEL_EDUCATIVO], [ID_MODALIDAD_EDUCATIVA], [CODIGO_NIVEL_EDUCATIVO], [DESCRIPCION_NIVEL_EDUCATIVO], [ABREVIATURA_NIVEL_EDUCATIVO], [ORDEN], [ACTIVO], [FECHA_CREACION], [USUARIO_CREACION], [IP_CREACION], [FECHA_MODIFICACION], [USUARIO_MODIFICACION], [IP_MODIFICACION]) VALUES (15, 5, N'17', N'CEO COMERCIAL', N'', NULL, 0, CAST(N'2021-07-20T12:13:14.423' AS DateTime), N'ADMIN', N'SISTEMAS', NULL, NULL, NULL)
INSERT [dbo].[nivel_educativo_temp] ([ID_NIVEL_EDUCATIVO], [ID_MODALIDAD_EDUCATIVA], [CODIGO_NIVEL_EDUCATIVO], [DESCRIPCION_NIVEL_EDUCATIVO], [ABREVIATURA_NIVEL_EDUCATIVO], [ORDEN], [ACTIVO], [FECHA_CREACION], [USUARIO_CREACION], [IP_CREACION], [FECHA_MODIFICACION], [USUARIO_MODIFICACION], [IP_MODIFICACION]) VALUES (16, 5, N'18', N'CEO ACADEMIA', N'', NULL, 0, CAST(N'2021-07-20T12:13:14.423' AS DateTime), N'ADMIN', N'SISTEMAS', NULL, NULL, NULL)
INSERT [dbo].[nivel_educativo_temp] ([ID_NIVEL_EDUCATIVO], [ID_MODALIDAD_EDUCATIVA], [CODIGO_NIVEL_EDUCATIVO], [DESCRIPCION_NIVEL_EDUCATIVO], [ABREVIATURA_NIVEL_EDUCATIVO], [ORDEN], [ACTIVO], [FECHA_CREACION], [USUARIO_CREACION], [IP_CREACION], [FECHA_MODIFICACION], [USUARIO_MODIFICACION], [IP_MODIFICACION]) VALUES (17, 5, N'19', N'CEO EDUC. SALUD', N'', NULL, 0, CAST(N'2021-07-20T12:13:14.423' AS DateTime), N'ADMIN', N'SISTEMAS', NULL, NULL, NULL)
INSERT [dbo].[nivel_educativo_temp] ([ID_NIVEL_EDUCATIVO], [ID_MODALIDAD_EDUCATIVA], [CODIGO_NIVEL_EDUCATIVO], [DESCRIPCION_NIVEL_EDUCATIVO], [ABREVIATURA_NIVEL_EDUCATIVO], [ORDEN], [ACTIVO], [FECHA_CREACION], [USUARIO_CREACION], [IP_CREACION], [FECHA_MODIFICACION], [USUARIO_MODIFICACION], [IP_MODIFICACION]) VALUES (18, 5, N'20', N'CEO MINERÍA PESQUERÍA', N'', NULL, 0, CAST(N'2021-07-20T12:13:14.423' AS DateTime), N'ADMIN', N'SISTEMAS', NULL, NULL, NULL)
INSERT [dbo].[nivel_educativo_temp] ([ID_NIVEL_EDUCATIVO], [ID_MODALIDAD_EDUCATIVA], [CODIGO_NIVEL_EDUCATIVO], [DESCRIPCION_NIVEL_EDUCATIVO], [ABREVIATURA_NIVEL_EDUCATIVO], [ORDEN], [ACTIVO], [FECHA_CREACION], [USUARIO_CREACION], [IP_CREACION], [FECHA_MODIFICACION], [USUARIO_MODIFICACION], [IP_MODIFICACION]) VALUES (19, 5, N'21', N'CEO TRANSPORTES Y COMUNICACIONES', N'', NULL, 0, CAST(N'2021-07-20T12:13:14.423' AS DateTime), N'ADMIN', N'SISTEMAS', NULL, NULL, NULL)
INSERT [dbo].[nivel_educativo_temp] ([ID_NIVEL_EDUCATIVO], [ID_MODALIDAD_EDUCATIVA], [CODIGO_NIVEL_EDUCATIVO], [DESCRIPCION_NIVEL_EDUCATIVO], [ABREVIATURA_NIVEL_EDUCATIVO], [ORDEN], [ACTIVO], [FECHA_CREACION], [USUARIO_CREACION], [IP_CREACION], [FECHA_MODIFICACION], [USUARIO_MODIFICACION], [IP_MODIFICACION]) VALUES (20, 5, N'22', N'CEO OTROS', N'', NULL, 0, CAST(N'2021-07-20T12:13:14.423' AS DateTime), N'ADMIN', N'SISTEMAS', NULL, NULL, NULL)
INSERT [dbo].[nivel_educativo_temp] ([ID_NIVEL_EDUCATIVO], [ID_MODALIDAD_EDUCATIVA], [CODIGO_NIVEL_EDUCATIVO], [DESCRIPCION_NIVEL_EDUCATIVO], [ABREVIATURA_NIVEL_EDUCATIVO], [ORDEN], [ACTIVO], [FECHA_CREACION], [USUARIO_CREACION], [IP_CREACION], [FECHA_MODIFICACION], [USUARIO_MODIFICACION], [IP_MODIFICACION]) VALUES (21, 6, N'23', N'ADMINISTRACIÓN', N'', NULL, 1, CAST(N'2021-07-20T12:13:14.423' AS DateTime), N'ADMIN', N'SISTEMAS', NULL, NULL, NULL)
INSERT [dbo].[nivel_educativo_temp] ([ID_NIVEL_EDUCATIVO], [ID_MODALIDAD_EDUCATIVA], [CODIGO_NIVEL_EDUCATIVO], [DESCRIPCION_NIVEL_EDUCATIVO], [ABREVIATURA_NIVEL_EDUCATIVO], [ORDEN], [ACTIVO], [FECHA_CREACION], [USUARIO_CREACION], [IP_CREACION], [FECHA_MODIFICACION], [USUARIO_MODIFICACION], [IP_MODIFICACION]) VALUES (22, 2, N'24', N'EBA - EDUCACIÓN BÁSICA ALTERNATIVA', N'', NULL, 0, CAST(N'2021-07-20T12:13:14.423' AS DateTime), N'ADMIN', N'SISTEMAS', NULL, NULL, NULL)
INSERT [dbo].[nivel_educativo_temp] ([ID_NIVEL_EDUCATIVO], [ID_MODALIDAD_EDUCATIVA], [CODIGO_NIVEL_EDUCATIVO], [DESCRIPCION_NIVEL_EDUCATIVO], [ABREVIATURA_NIVEL_EDUCATIVO], [ORDEN], [ACTIVO], [FECHA_CREACION], [USUARIO_CREACION], [IP_CREACION], [FECHA_MODIFICACION], [USUARIO_MODIFICACION], [IP_MODIFICACION]) VALUES (23, 3, N'35', N'EBE - EDUCACIÓN ESPECIAL', N'', NULL, 1, CAST(N'2021-07-20T12:13:14.423' AS DateTime), N'ADMIN', N'SISTEMAS', NULL, NULL, NULL)
INSERT [dbo].[nivel_educativo_temp] ([ID_NIVEL_EDUCATIVO], [ID_MODALIDAD_EDUCATIVA], [CODIGO_NIVEL_EDUCATIVO], [DESCRIPCION_NIVEL_EDUCATIVO], [ABREVIATURA_NIVEL_EDUCATIVO], [ORDEN], [ACTIVO], [FECHA_CREACION], [USUARIO_CREACION], [IP_CREACION], [FECHA_MODIFICACION], [USUARIO_MODIFICACION], [IP_MODIFICACION]) VALUES (24, 2, N'37', N'EBA - PRIMARIA DE ADULTOS', N'', NULL, 0, CAST(N'2021-07-20T12:13:14.427' AS DateTime), N'ADMIN', N'SISTEMAS', NULL, NULL, NULL)
INSERT [dbo].[nivel_educativo_temp] ([ID_NIVEL_EDUCATIVO], [ID_MODALIDAD_EDUCATIVA], [CODIGO_NIVEL_EDUCATIVO], [DESCRIPCION_NIVEL_EDUCATIVO], [ABREVIATURA_NIVEL_EDUCATIVO], [ORDEN], [ACTIVO], [FECHA_CREACION], [USUARIO_CREACION], [IP_CREACION], [FECHA_MODIFICACION], [USUARIO_MODIFICACION], [IP_MODIFICACION]) VALUES (25, 2, N'38', N'EBA - SECUNDARIA DE ADULTOS', N'', NULL, 0, CAST(N'2021-07-20T12:13:14.427' AS DateTime), N'ADMIN', N'SISTEMAS', NULL, NULL, NULL)
INSERT [dbo].[nivel_educativo_temp] ([ID_NIVEL_EDUCATIVO], [ID_MODALIDAD_EDUCATIVA], [CODIGO_NIVEL_EDUCATIVO], [DESCRIPCION_NIVEL_EDUCATIVO], [ABREVIATURA_NIVEL_EDUCATIVO], [ORDEN], [ACTIVO], [FECHA_CREACION], [USUARIO_CREACION], [IP_CREACION], [FECHA_MODIFICACION], [USUARIO_MODIFICACION], [IP_MODIFICACION]) VALUES (26, 2, N'40', N'EBA - INICIAL E INTERMEDIO', N'', NULL, 1, CAST(N'2021-07-20T12:13:14.427' AS DateTime), N'ADMIN', N'SISTEMAS', NULL, NULL, NULL)
INSERT [dbo].[nivel_educativo_temp] ([ID_NIVEL_EDUCATIVO], [ID_MODALIDAD_EDUCATIVA], [CODIGO_NIVEL_EDUCATIVO], [DESCRIPCION_NIVEL_EDUCATIVO], [ABREVIATURA_NIVEL_EDUCATIVO], [ORDEN], [ACTIVO], [FECHA_CREACION], [USUARIO_CREACION], [IP_CREACION], [FECHA_MODIFICACION], [USUARIO_MODIFICACION], [IP_MODIFICACION]) VALUES (27, 2, N'41', N'EBA - AVANZADO', N'', NULL, 1, CAST(N'2021-07-20T12:13:14.427' AS DateTime), N'ADMIN', N'SISTEMAS', NULL, NULL, NULL)
INSERT [dbo].[nivel_educativo_temp] ([ID_NIVEL_EDUCATIVO], [ID_MODALIDAD_EDUCATIVA], [CODIGO_NIVEL_EDUCATIVO], [DESCRIPCION_NIVEL_EDUCATIVO], [ABREVIATURA_NIVEL_EDUCATIVO], [ORDEN], [ACTIVO], [FECHA_CREACION], [USUARIO_CREACION], [IP_CREACION], [FECHA_MODIFICACION], [USUARIO_MODIFICACION], [IP_MODIFICACION]) VALUES (28, 8, N'99', N'INICIAL - PROGRAMA NO ESCOLARIZADO', N'', NULL, 0, CAST(N'2021-07-20T12:13:14.427' AS DateTime), N'ADMIN', N'SISTEMAS', NULL, NULL, NULL)
INSERT [dbo].[nivel_educativo_temp] ([ID_NIVEL_EDUCATIVO], [ID_MODALIDAD_EDUCATIVA], [CODIGO_NIVEL_EDUCATIVO], [DESCRIPCION_NIVEL_EDUCATIVO], [ABREVIATURA_NIVEL_EDUCATIVO], [ORDEN], [ACTIVO], [FECHA_CREACION], [USUARIO_CREACION], [IP_CREACION], [FECHA_MODIFICACION], [USUARIO_MODIFICACION], [IP_MODIFICACION]) VALUES (29, 7, N'900', N'NO APLICA', N'', NULL, 1, CAST(N'2021-07-20T12:13:14.427' AS DateTime), N'ADMIN', N'SISTEMAS', NULL, NULL, NULL)
INSERT [dbo].[nivel_educativo_temp] ([ID_NIVEL_EDUCATIVO], [ID_MODALIDAD_EDUCATIVA], [CODIGO_NIVEL_EDUCATIVO], [DESCRIPCION_NIVEL_EDUCATIVO], [ABREVIATURA_NIVEL_EDUCATIVO], [ORDEN], [ACTIVO], [FECHA_CREACION], [USUARIO_CREACION], [IP_CREACION], [FECHA_MODIFICACION], [USUARIO_MODIFICACION], [IP_MODIFICACION]) VALUES (30, 8, N'901', N'NO ESPECIFICADO', N'', NULL, 0, CAST(N'2021-07-20T12:13:14.427' AS DateTime), N'ADMIN', N'SISTEMAS', NULL, NULL, NULL)
GO

update  ca
SET 
    ca.ID_MODALIDAD_EDUCATIVA=  c.ID_MODALIDAD_EDUCATIVA,
    ca.CODIGO_NIVEL_EDUCATIVO=  c.CODIGO_NIVEL_EDUCATIVO,
	ca.DESCRIPCION_NIVEL_EDUCATIVO=  c.DESCRIPCION_NIVEL_EDUCATIVO,
	ca.ABREVIATURA_NIVEL_EDUCATIVO=  c.ABREVIATURA_NIVEL_EDUCATIVO,
	ca.ORDEN=  c.ORDEN,
	ca.ACTIVO=  c.ACTIVO,
	ca.FECHA_MODIFICACION=GETDATE(),
	ca.USUARIO_CREACION='MIGRA'
from nivel_educativo_temp  c inner join nivel_educativo ca  on c.ID_NIVEL_EDUCATIVO=ca.ID_NIVEL_EDUCATIVO


GO
--- Insertamos nuevos Cargos
insert into nivel_educativo
SELECT 
c.*
from nivel_educativo_temp  c left join nivel_educativo ca  on c.ID_NIVEL_EDUCATIVO=ca.ID_NIVEL_EDUCATIVO
where 
  ca.ID_NIVEL_EDUCATIVO is null

GO 
-- eliminamos tabla temporal

drop table nivel_educativo_temp

---

GO
alter sequence seq_nivel_educativo restart with 31;